spring:

  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000

  #Profile
  profiles:
    active: dev, prod

  #liquibase
  liquibase:
    changelog: db/changelog/V1__Default_Models.sql

  # Hibernate Settings
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081

  logging:
    level:
      org.springframework.security: DEBUG