# Database Configuration (Data Source)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/NewsSecurityServer
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_SECURITY_USER}
    password: ${POSTGRES_SECURITY_PASSWORD}